
version: '3.9'


services:

#nextjs service
  nextjs:
    build:
      context: ./services/nextjs
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VAULT_ADDR=http://vault:8200
    networks:
      - main-network
    depends_on:
      - vault

#vault service
  vault:
    image: hashicorp/vault:latest
    container_name: vault_service
    restart: unless-stopped
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_ROOT_TOKEN:-myroot}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      - main-network

 #prometheus and grafana services for monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - main-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - main-network
    depends_on:
      - prometheus


#Uptime Kuma for uptime monitoring && Notification
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime_kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data
    networks:
      - main-network


#Node Exporter for system metrics scraping by Prometheus
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - main-network

volumes:
  prometheus_data:
  grafana_data:
  uptime_kuma_data:


networks:
  main-network:
    driver: bridge