global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nextjs_app'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['nextjs_app:3000']

  # 2. Vault
  - job_name: 'vault'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['vault_service:8200']

  # 3. Node Exporter
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node_exporter:9100']